language: go
go: "1.11.1"

notifications:
  email: false

install:
  - go get -v github.com/gobuffalo/packr/v2/...

script:
  - ./build.sh

before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: releases
  api_key:
    secure: XjXKTZ5Rwb9oPi9+AP6RJRjx3rGw93XB3IdmKp+z5YX/2/1oGLW1p8wNF6N3U2bL0zZ7XIzzUWtDapus4a0fzB98oTG7W4kw0DgZYZ2zL5lLeOM72hLKGTWDS09HJh6KPvhPCPy/XQp0Mofu6lekGM5YhtMv68i2nLxC2Jg8+ngfs/Jntz5ZqCSe+KzBj4ewYMF0FfMIty4mrg5inZ5Ss0FN0zbeEasdbesQj64epALN3D8hg4qgULsJsYJ71MEfZLmfNpz0zxx1hV48Ehgd2DSB/mVJ35lVkT/REEBWuqj4NmlcfTWr7TmP2Lxit0Raytslqui9JLWN3wku1X0oToIooJJlKVp172eICCXtL4/9TmK7GXgwO0FXeT+y5PUNaSMyb3OrwnsWoCAYBvGNfYO3RmJJHMvGmTj1q235x+HxaYHjzQuNbh2AAblLY8+8Z5Ggr+BX/XwnAFRqA5ZcIXWC6bnNAhh3Q+4f59bAvEP37E3gYmVSXalOhoh/bmQRJHhZC9udRkTo4XiHogPgjbJH/J8qxa0JXsRgdHsF2pgCZ+OdhH2JIzSjsrAF/uqzWoKb6u/voe30UvdG6G2eW6mmLOrfOv81B9SH92lWBJcN6VTN/JE18byElTCTZsV+i1eSb8wtu1jJ1Fm8in1wpAjQsrQczk+U9YavuUqiHjw=
  file_glob: true
  file: release/*.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: JeziL/gosvr